---
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maven-builder
    volumes:
      - app_volume:/war

  runner:
    image: tomcat:9.0.98-jdk11
    container_name: tomcat-runner
    depends_on:
      - builder
    volumes:
      - app_volume:/usr/local/tomcat/webapps/
    ports:
      - "8081:8080"
    entrypoint: >
      sh -c "while [ ! -f /usr/local/tomcat/webapps/ROOT.war ]; do
               echo 'Waiting for WAR file...';
               sleep 2;
             done;
             /usr/local/tomcat/bin/catalina.sh run"

volumes:
  app_volume: